-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity folo_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    layer4_out_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    layer4_out_empty_n : IN STD_LOGIC;
    layer4_out_read : OUT STD_LOGIC;
    layer4_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
    layer4_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
    layer18_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    layer18_out_full_n : IN STD_LOGIC;
    layer18_out_write : OUT STD_LOGIC;
    layer18_out_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    layer18_out_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of folo_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_s is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv8_A0 : STD_LOGIC_VECTOR (7 downto 0) := "10100000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal layer18_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal i_6_fu_92_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal i_6_reg_112 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_start : STD_LOGIC;
    signal grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_done : STD_LOGIC;
    signal grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_idle : STD_LOGIC;
    signal grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_ready : STD_LOGIC;
    signal grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer4_out_read : STD_LOGIC;
    signal grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_write : STD_LOGIC;
    signal grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_num_data_valid : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_fifo_cap : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_start : STD_LOGIC;
    signal grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_done : STD_LOGIC;
    signal grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_idle : STD_LOGIC;
    signal grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_ready : STD_LOGIC;
    signal grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_layer18_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_layer18_out_write : STD_LOGIC;
    signal grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln59_fu_86_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal i_fu_38 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_block_state1 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component folo_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        layer4_out_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        layer4_out_empty_n : IN STD_LOGIC;
        layer4_out_read : OUT STD_LOGIC;
        layer4_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
        layer4_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
        layer18_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        layer18_out_full_n : IN STD_LOGIC;
        layer18_out_write : OUT STD_LOGIC;
        layer18_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
        layer18_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component folo_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        layer18_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        layer18_out_full_n : IN STD_LOGIC;
        layer18_out_write : OUT STD_LOGIC;
        layer18_out_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        layer18_out_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50 : component folo_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_start,
        ap_done => grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_done,
        ap_idle => grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_idle,
        ap_ready => grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_ready,
        layer4_out_dout => layer4_out_dout,
        layer4_out_empty_n => layer4_out_empty_n,
        layer4_out_read => grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer4_out_read,
        layer4_out_num_data_valid => ap_const_lv11_0,
        layer4_out_fifo_cap => ap_const_lv11_0,
        layer18_out_din => grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_din,
        layer18_out_full_n => layer18_out_full_n,
        layer18_out_write => grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_write,
        layer18_out_num_data_valid => grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_num_data_valid,
        layer18_out_fifo_cap => grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_fifo_cap);

    grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58 : component folo_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_start,
        ap_done => grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_done,
        ap_idle => grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_idle,
        ap_ready => grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_ready,
        layer18_out_din => grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_layer18_out_din,
        layer18_out_full_n => layer18_out_full_n,
        layer18_out_write => grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_layer18_out_write,
        layer18_out_num_data_valid => layer18_out_num_data_valid,
        layer18_out_fifo_cap => layer18_out_fifo_cap);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln59_fu_86_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_ready = ap_const_logic_1)) then 
                    grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln59_fu_86_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_ready = ap_const_logic_1)) then 
                    grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_fu_38_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                i_fu_38 <= ap_const_lv8_0;
            elsif (((layer18_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                i_fu_38 <= i_6_reg_112;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_6_reg_112 <= i_6_fu_92_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, layer18_out_full_n, ap_CS_fsm_state4, ap_CS_fsm_state2, grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_done, grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_done, icmp_ln59_fu_86_p2, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln59_fu_86_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((layer18_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_done)
    begin
        if ((grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(layer18_out_full_n)
    begin
        if ((layer18_out_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_done)
    begin
        if ((grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_done, ap_CS_fsm_state5)
    begin
        if (((grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_start <= grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_start_reg;
    grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_start <= grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_start_reg;
    
    grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_fifo_cap_proc : process(layer18_out_fifo_cap)
    variable vlo_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_fifo_cap_i : integer;
    variable section : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(5 - 1 downto 0) := ap_const_lv32_0(5 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(5 - 1 downto 0) := ap_const_lv32_A(5 - 1 downto 0);
        v0_cpy := layer18_out_fifo_cap;
        if (vlo_cpy(5 - 1 downto 0) > vhi_cpy(5 - 1 downto 0)) then
            vhi_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_A(5-1 downto 0)));
            vlo_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_0(5-1 downto 0)));
            for grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_fifo_cap_i in 0 to 32-1 loop
                v0_cpy(grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_fifo_cap_i) := layer18_out_fifo_cap(32-1-grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_fifo_cap_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(5-1 downto 0)))));

        section := (others=>'0');
        section(5-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(5-1 downto 0)) - unsigned(vlo_cpy(5-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(32-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_fifo_cap <= resvalue(11-1 downto 0);
    end process;

    
    grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_num_data_valid_proc : process(layer18_out_num_data_valid)
    variable vlo_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_num_data_valid_i : integer;
    variable section : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(5 - 1 downto 0) := ap_const_lv32_0(5 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(5 - 1 downto 0) := ap_const_lv32_A(5 - 1 downto 0);
        v0_cpy := layer18_out_num_data_valid;
        if (vlo_cpy(5 - 1 downto 0) > vhi_cpy(5 - 1 downto 0)) then
            vhi_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_A(5-1 downto 0)));
            vlo_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_0(5-1 downto 0)));
            for grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_num_data_valid_i in 0 to 32-1 loop
                v0_cpy(grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_num_data_valid_i) := layer18_out_num_data_valid(32-1-grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_num_data_valid_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(5-1 downto 0)))));

        section := (others=>'0');
        section(5-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(5-1 downto 0)) - unsigned(vlo_cpy(5-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(32-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_num_data_valid <= resvalue(11-1 downto 0);
    end process;

    i_6_fu_92_p2 <= std_logic_vector(unsigned(i_fu_38) + unsigned(ap_const_lv8_1));
    icmp_ln59_fu_86_p2 <= "1" when (i_fu_38 = ap_const_lv8_A0) else "0";

    internal_ap_ready_assign_proc : process(grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_done, ap_CS_fsm_state5)
    begin
        if (((grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    layer18_out_blk_n_assign_proc : process(layer18_out_full_n, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            layer18_out_blk_n <= layer18_out_full_n;
        else 
            layer18_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer18_out_din_assign_proc : process(layer18_out_full_n, ap_CS_fsm_state4, grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_din, grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_layer18_out_din, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if (((layer18_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            layer18_out_din <= ap_const_lv32_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            layer18_out_din <= grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_layer18_out_din;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            layer18_out_din <= grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_din;
        else 
            layer18_out_din <= grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_layer18_out_din;
        end if; 
    end process;


    layer18_out_write_assign_proc : process(layer18_out_full_n, ap_CS_fsm_state4, grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_write, grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_layer18_out_write, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if (((layer18_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            layer18_out_write <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            layer18_out_write <= grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_layer18_out_write;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            layer18_out_write <= grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_write;
        else 
            layer18_out_write <= ap_const_logic_0;
        end if; 
    end process;

    layer4_out_read <= grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer4_out_read;

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
