-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity folo_shift_line_buffer_array_ap_ufixed_8_0_4_0_0_4u_config5_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_i : IN STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_o_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_19 : OUT STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_19_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_i : IN STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18 : OUT STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_i : IN STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17 : OUT STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_i : IN STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_o_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16 : OUT STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_63_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_63_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_63_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_67 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_67_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_62_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_62_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_62_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_66 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_66_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_61_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_61_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_61_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_65 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_65_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_60_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_60_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_60_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_64 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_64_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_51_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_51_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_51_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_55 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_55_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_50_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_50_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_50_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_54 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_54_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_49_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_49_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_49_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_53 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_53_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_48_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_48_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_48_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_52 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_52_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_i : IN STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_i : IN STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_69_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_69_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_69_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_68_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_68_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_68_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_59_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_59_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_59_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_58_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_58_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_58_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_57_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_57_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_57_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_56_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_56_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_56_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_47_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_47_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_47_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_46_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_46_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_46_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_45_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_45_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_45_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_44_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_44_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_44_o_ap_vld : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC );
end;


architecture behav of folo_shift_line_buffer_array_ap_ufixed_8_0_4_0_0_4u_config5_s is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_A0 : STD_LOGIC_VECTOR (7 downto 0) := "10100000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_19_ce0 : STD_LOGIC;
    signal p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_19_we0 : STD_LOGIC;
    signal p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_19_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_15_ce0 : STD_LOGIC;
    signal p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_15_we0 : STD_LOGIC;
    signal p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_15_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_18_ce0 : STD_LOGIC;
    signal p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_18_we0 : STD_LOGIC;
    signal p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_18_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_14_ce0 : STD_LOGIC;
    signal p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_14_we0 : STD_LOGIC;
    signal p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_14_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_17_ce0 : STD_LOGIC;
    signal p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_17_we0 : STD_LOGIC;
    signal p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_17_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_13_ce0 : STD_LOGIC;
    signal p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_13_we0 : STD_LOGIC;
    signal p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_13_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_16_ce0 : STD_LOGIC;
    signal p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_16_we0 : STD_LOGIC;
    signal p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_16_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_12_ce0 : STD_LOGIC;
    signal p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_12_we0 : STD_LOGIC;
    signal p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_12_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component folo_shift_line_buffer_array_ap_ufixed_8_0_4_0_0_4u_config5_s_p_ZZN4nnet26conv_2d_dEe IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_19_U : component folo_shift_line_buffer_array_ap_ufixed_8_0_4_0_0_4u_config5_s_p_ZZN4nnet26conv_2d_dEe
    generic map (
        DataWidth => 8,
        AddressRange => 161,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv8_A0,
        ce0 => p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_19_ce0,
        we0 => p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_19_we0,
        d0 => p_read,
        q0 => p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_19_q0);

    p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_15_U : component folo_shift_line_buffer_array_ap_ufixed_8_0_4_0_0_4u_config5_s_p_ZZN4nnet26conv_2d_dEe
    generic map (
        DataWidth => 8,
        AddressRange => 161,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv8_A0,
        ce0 => p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_15_ce0,
        we0 => p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_15_we0,
        d0 => p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_19_q0,
        q0 => p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_15_q0);

    p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_18_U : component folo_shift_line_buffer_array_ap_ufixed_8_0_4_0_0_4u_config5_s_p_ZZN4nnet26conv_2d_dEe
    generic map (
        DataWidth => 8,
        AddressRange => 161,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv8_A0,
        ce0 => p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_18_ce0,
        we0 => p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_18_we0,
        d0 => p_read1,
        q0 => p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_18_q0);

    p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_14_U : component folo_shift_line_buffer_array_ap_ufixed_8_0_4_0_0_4u_config5_s_p_ZZN4nnet26conv_2d_dEe
    generic map (
        DataWidth => 8,
        AddressRange => 161,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv8_A0,
        ce0 => p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_14_ce0,
        we0 => p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_14_we0,
        d0 => p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_18_q0,
        q0 => p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_14_q0);

    p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_17_U : component folo_shift_line_buffer_array_ap_ufixed_8_0_4_0_0_4u_config5_s_p_ZZN4nnet26conv_2d_dEe
    generic map (
        DataWidth => 8,
        AddressRange => 161,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv8_A0,
        ce0 => p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_17_ce0,
        we0 => p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_17_we0,
        d0 => p_read2,
        q0 => p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_17_q0);

    p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_13_U : component folo_shift_line_buffer_array_ap_ufixed_8_0_4_0_0_4u_config5_s_p_ZZN4nnet26conv_2d_dEe
    generic map (
        DataWidth => 8,
        AddressRange => 161,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv8_A0,
        ce0 => p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_13_ce0,
        we0 => p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_13_we0,
        d0 => p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_17_q0,
        q0 => p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_13_q0);

    p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_16_U : component folo_shift_line_buffer_array_ap_ufixed_8_0_4_0_0_4u_config5_s_p_ZZN4nnet26conv_2d_dEe
    generic map (
        DataWidth => 8,
        AddressRange => 161,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv8_A0,
        ce0 => p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_16_ce0,
        we0 => p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_16_we0,
        d0 => p_read3,
        q0 => p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_16_q0);

    p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_12_U : component folo_shift_line_buffer_array_ap_ufixed_8_0_4_0_0_4u_config5_s_p_ZZN4nnet26conv_2d_dEe
    generic map (
        DataWidth => 8,
        AddressRange => 161,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv8_A0,
        ce0 => p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_12_ce0,
        we0 => p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_12_we0,
        d0 => p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_16_q0,
        q0 => p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_12_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_ce)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_ce)
    begin
        if (((ap_start = ap_const_logic_0) or (ap_const_logic_0 = ap_ce))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_44_o_assign_proc : process(ap_CS_fsm_state1, p_read3, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_44_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_44_o <= p_read3;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_44_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_44_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_44_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_44_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_44_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_45_o_assign_proc : process(ap_CS_fsm_state1, p_read2, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_45_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_45_o <= p_read2;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_45_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_45_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_45_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_45_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_45_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_46_o_assign_proc : process(ap_CS_fsm_state1, p_read1, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_46_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_46_o <= p_read1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_46_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_46_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_46_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_46_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_46_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_47_o_assign_proc : process(ap_CS_fsm_state1, p_read, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_47_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_47_o <= p_read;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_47_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_47_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_47_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_47_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_47_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_48_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_48_i, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_44_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_48_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_44_i;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_48_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_48_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_48_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_48_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_48_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_49_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_49_i, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_45_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_49_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_45_i;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_49_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_49_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_49_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_49_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_49_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_50_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_50_i, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_46_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_50_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_46_i;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_50_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_50_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_50_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_50_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_50_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_51_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_51_i, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_47_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_51_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_47_i;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_51_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_51_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_51_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_51_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_51_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_52 <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_48_i;

    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_52_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_52_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_52_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_53 <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_49_i;

    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_53_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_53_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_53_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_54 <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_50_i;

    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_54_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_54_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_54_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_55 <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_51_i;

    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_55_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_55_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_55_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_56_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_56_i, p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_16_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_56_o <= p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_16_q0;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_56_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_56_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_56_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_56_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_56_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_57_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_57_i, p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_17_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_57_o <= p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_17_q0;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_57_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_57_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_57_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_57_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_57_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_58_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_58_i, p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_18_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_58_o <= p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_18_q0;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_58_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_58_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_58_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_58_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_58_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_59_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_59_i, p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_19_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_59_o <= p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_19_q0;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_59_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_59_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_59_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_59_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_59_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_60_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_60_i, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_56_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_60_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_56_i;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_60_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_60_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_60_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_60_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_60_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_61_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_61_i, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_57_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_61_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_57_i;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_61_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_61_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_61_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_61_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_61_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_62_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_62_i, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_58_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_62_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_58_i;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_62_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_62_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_62_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_62_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_62_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_63_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_63_i, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_59_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_63_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_59_i;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_63_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_63_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_63_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_63_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_63_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_64 <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_60_i;

    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_64_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_64_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_64_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_65 <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_61_i;

    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_65_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_65_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_65_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_66 <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_62_i;

    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_66_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_66_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_66_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_67 <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_63_i;

    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_67_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_67_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_67_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_68_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_68_i, p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_12_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_68_o <= p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_12_q0;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_68_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_68_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_68_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_68_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_68_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_69_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_69_i, p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_13_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_69_o <= p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_13_q0;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_69_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_69_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_69_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_69_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_69_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_12_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_12_ce0 <= ap_const_logic_1;
        else 
            p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_12_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_12_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_12_we0 <= ap_const_logic_1;
        else 
            p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_12_we0 <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_13_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_13_ce0 <= ap_const_logic_1;
        else 
            p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_13_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_13_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_13_we0 <= ap_const_logic_1;
        else 
            p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_13_we0 <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_14_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_14_ce0 <= ap_const_logic_1;
        else 
            p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_14_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_14_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_14_we0 <= ap_const_logic_1;
        else 
            p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_14_we0 <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_15_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_15_ce0 <= ap_const_logic_1;
        else 
            p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_15_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_15_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_15_we0 <= ap_const_logic_1;
        else 
            p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_15_we0 <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_16_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_16_ce0 <= ap_const_logic_1;
        else 
            p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_16_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_16_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_16_we0 <= ap_const_logic_1;
        else 
            p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_16_we0 <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_17_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_17_ce0 <= ap_const_logic_1;
        else 
            p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_17_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_17_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_17_we0 <= ap_const_logic_1;
        else 
            p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_17_we0 <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_18_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_18_ce0 <= ap_const_logic_1;
        else 
            p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_18_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_18_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_18_we0 <= ap_const_logic_1;
        else 
            p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_18_we0 <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_19_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_19_ce0 <= ap_const_logic_1;
        else 
            p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_19_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_19_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_19_we0 <= ap_const_logic_1;
        else 
            p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_19_we0 <= ap_const_logic_0;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o_assign_proc : process(ap_CS_fsm_state1, void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_i, p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_14_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o <= p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_14_q0;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_i;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o_assign_proc : process(ap_CS_fsm_state1, void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_i, p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_15_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o <= p_ZZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4E_15_q0;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_i;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_o_assign_proc : process(ap_CS_fsm_state1, void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_i, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_68_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_68_i;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_o <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_i;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_o_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o_assign_proc : process(ap_CS_fsm_state1, void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_i, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_69_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9_69_i;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_i;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o_assign_proc : process(ap_CS_fsm_state1, void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_i, void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_i;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_i;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_o_assign_proc : process(ap_CS_fsm_state1, void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_i, void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_o <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_i;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_o <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_i;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_o_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_i;

    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_i;

    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_i;

    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_19 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_i;

    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_19_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_19_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_19_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

end behav;
