// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module folo_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer4_out_dout,
        layer4_out_empty_n,
        layer4_out_read,
        layer4_out_num_data_valid,
        layer4_out_fifo_cap,
        layer18_out_din,
        layer18_out_full_n,
        layer18_out_write,
        layer18_out_num_data_valid,
        layer18_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] layer4_out_dout;
input   layer4_out_empty_n;
output   layer4_out_read;
input  [10:0] layer4_out_num_data_valid;
input  [10:0] layer4_out_fifo_cap;
output  [31:0] layer18_out_din;
input   layer18_out_full_n;
output   layer18_out_write;
input  [31:0] layer18_out_num_data_valid;
input  [31:0] layer18_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg[31:0] layer18_out_din;
reg layer18_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer18_out_blk_n;
wire    ap_CS_fsm_state4;
wire   [7:0] i_6_fu_92_p2;
reg   [7:0] i_6_reg_112;
wire    ap_CS_fsm_state2;
wire    grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_start;
wire    grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_done;
wire    grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_idle;
wire    grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_ready;
wire    grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer4_out_read;
wire   [31:0] grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_din;
wire    grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_write;
wire   [10:0] grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_num_data_valid;
wire   [10:0] grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_fifo_cap;
wire    grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_start;
wire    grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_done;
wire    grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_idle;
wire    grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_ready;
wire   [31:0] grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_layer18_out_din;
wire    grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_layer18_out_write;
reg    grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_start_reg;
wire   [0:0] icmp_ln59_fu_86_p2;
wire    ap_CS_fsm_state3;
reg    grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_start_reg;
wire    ap_CS_fsm_state5;
reg   [7:0] i_fu_38;
reg    ap_block_state1;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_start_reg = 1'b0;
#0 grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_start_reg = 1'b0;
#0 i_fu_38 = 8'd0;
end

folo_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_start),
    .ap_done(grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_done),
    .ap_idle(grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_idle),
    .ap_ready(grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_ready),
    .layer4_out_dout(layer4_out_dout),
    .layer4_out_empty_n(layer4_out_empty_n),
    .layer4_out_read(grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer4_out_read),
    .layer4_out_num_data_valid(11'd0),
    .layer4_out_fifo_cap(11'd0),
    .layer18_out_din(grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_din),
    .layer18_out_full_n(layer18_out_full_n),
    .layer18_out_write(grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_write),
    .layer18_out_num_data_valid(grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_num_data_valid),
    .layer18_out_fifo_cap(grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_fifo_cap)
);

folo_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_start),
    .ap_done(grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_done),
    .ap_idle(grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_idle),
    .ap_ready(grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_ready),
    .layer18_out_din(grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_layer18_out_din),
    .layer18_out_full_n(layer18_out_full_n),
    .layer18_out_write(grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_layer18_out_write),
    .layer18_out_num_data_valid(layer18_out_num_data_valid),
    .layer18_out_fifo_cap(layer18_out_fifo_cap)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln59_fu_86_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_start_reg <= 1'b1;
        end else if ((grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_ready == 1'b1)) begin
            grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln59_fu_86_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_start_reg <= 1'b1;
        end else if ((grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_ready == 1'b1)) begin
            grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        i_fu_38 <= 8'd0;
    end else if (((layer18_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        i_fu_38 <= i_6_reg_112;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_6_reg_112 <= i_6_fu_92_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((layer18_out_full_n == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        layer18_out_blk_n = layer18_out_full_n;
    end else begin
        layer18_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer18_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        layer18_out_din = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        layer18_out_din = grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_layer18_out_din;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        layer18_out_din = grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_din;
    end else begin
        layer18_out_din = grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_layer18_out_din;
    end
end

always @ (*) begin
    if (((layer18_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        layer18_out_write = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        layer18_out_write = grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_layer18_out_write;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        layer18_out_write = grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_write;
    end else begin
        layer18_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln59_fu_86_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((layer18_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_start = grp_zeropad2d_cl_array_array_ap_ufixed_4u_config18_Pipeline_PadBottomWidth_fu_58_ap_start_reg;

assign grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_start = grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_ap_start_reg;

assign grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_fifo_cap = {{layer18_out_fifo_cap[10:0]}};

assign grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer18_out_num_data_valid = {{layer18_out_num_data_valid[10:0]}};

assign i_6_fu_92_p2 = (i_fu_38 + 8'd1);

assign icmp_ln59_fu_86_p2 = ((i_fu_38 == 8'd160) ? 1'b1 : 1'b0);

assign layer4_out_read = grp_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_Pipeline_CopyMain_fu_50_layer4_out_read;

assign start_out = real_start;

endmodule //folo_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_s
