// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="folo_folo,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcku035-fbva676-2-e,HLS_INPUT_CLOCK=2.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=3.463000,HLS_SYN_LAT=466759,HLS_SYN_TPT=466578,HLS_SYN_MEM=16,HLS_SYN_DSP=0,HLS_SYN_FF=36812,HLS_SYN_LUT=31444,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module folo (
        input_3_TDATA,
        layer16_out_TDATA,
        ap_clk,
        ap_rst_n,
        input_3_TVALID,
        input_3_TREADY,
        ap_start,
        layer16_out_TVALID,
        layer16_out_TREADY,
        ap_done,
        ap_ready,
        ap_idle
);


input  [15:0] input_3_TDATA;
output  [15:0] layer16_out_TDATA;
input   ap_clk;
input   ap_rst_n;
input   input_3_TVALID;
output   input_3_TREADY;
input   ap_start;
output   layer16_out_TVALID;
input   layer16_out_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire    zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_ap_start;
wire    zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_ap_done;
wire    zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_ap_continue;
wire    zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_ap_idle;
wire    zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_ap_ready;
wire    zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_start_out;
wire    zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_start_write;
wire    zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_input_3_TREADY;
wire   [15:0] zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_layer17_out_din;
wire    zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_layer17_out_write;
wire   [31:0] zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_layer17_out_num_data_valid;
wire   [31:0] zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_layer17_out_fifo_cap;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_ap_start;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_ap_done;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_ap_continue;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_ap_idle;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_ap_ready;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_layer17_out_read;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_start_out;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_start_write;
wire   [115:0] conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_layer2_out_din;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_layer2_out_write;
wire    relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_ap_start;
wire    relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_ap_done;
wire    relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_ap_continue;
wire    relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_ap_idle;
wire    relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_ap_ready;
wire    relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_layer2_out_read;
wire   [31:0] relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_layer4_out_din;
wire    relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_layer4_out_write;
wire   [31:0] relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_layer4_out_num_data_valid;
wire   [31:0] relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_layer4_out_fifo_cap;
wire    relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_start_out;
wire    relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_start_write;
wire    zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_ap_start;
wire    zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_ap_done;
wire    zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_ap_continue;
wire    zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_ap_idle;
wire    zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_ap_ready;
wire    zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_start_out;
wire    zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_start_write;
wire    zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_layer4_out_read;
wire   [31:0] zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_layer18_out_din;
wire    zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_layer18_out_write;
wire   [31:0] zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_layer18_out_num_data_valid;
wire   [31:0] zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_layer18_out_fifo_cap;
wire    conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_ap_start;
wire    conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_ap_done;
wire    conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_ap_continue;
wire    conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_ap_idle;
wire    conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_ap_ready;
wire    conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_start_out;
wire    conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_start_write;
wire    conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_layer18_out_read;
wire   [137:0] conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_layer5_out_din;
wire    conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_layer5_out_write;
wire    relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_ap_start;
wire    relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_ap_done;
wire    relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_ap_continue;
wire    relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_ap_idle;
wire    relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_ap_ready;
wire    relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_layer5_out_read;
wire   [47:0] relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_layer7_out_din;
wire    relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_layer7_out_write;
wire   [31:0] relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_layer7_out_num_data_valid;
wire   [31:0] relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_layer7_out_fifo_cap;
wire    relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_start_out;
wire    relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_start_write;
wire    zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_ap_start;
wire    zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_ap_done;
wire    zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_ap_continue;
wire    zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_ap_idle;
wire    zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_ap_ready;
wire    zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_start_out;
wire    zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_start_write;
wire    zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_layer7_out_read;
wire   [47:0] zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_layer19_out_din;
wire    zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_layer19_out_write;
wire   [31:0] zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_layer19_out_num_data_valid;
wire   [31:0] zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_layer19_out_fifo_cap;
wire    conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_ap_start;
wire    conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_ap_done;
wire    conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_ap_continue;
wire    conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_ap_idle;
wire    conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_ap_ready;
wire    conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_start_out;
wire    conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_start_write;
wire    conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_layer19_out_read;
wire   [183:0] conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_layer8_out_din;
wire    conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_layer8_out_write;
wire    relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_ap_start;
wire    relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_ap_done;
wire    relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_ap_continue;
wire    relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_ap_idle;
wire    relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_ap_ready;
wire    relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_layer8_out_read;
wire   [63:0] relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_layer10_out_din;
wire    relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_layer10_out_write;
wire   [31:0] relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_layer10_out_num_data_valid;
wire   [31:0] relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_layer10_out_fifo_cap;
wire    relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_start_out;
wire    relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_start_write;
wire    pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_ap_start;
wire    pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_ap_done;
wire    pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_ap_continue;
wire    pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_ap_idle;
wire    pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_ap_ready;
wire    pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_layer10_out_read;
wire   [223:0] pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_layer11_out_din;
wire    pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_layer11_out_write;
wire   [31:0] pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_layer11_out_num_data_valid;
wire   [31:0] pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_layer11_out_fifo_cap;
wire    pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_start_out;
wire    pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_start_write;
wire    relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_ap_start;
wire    relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_ap_done;
wire    relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_ap_continue;
wire    relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_ap_idle;
wire    relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_ap_ready;
wire    relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_start_out;
wire    relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_start_write;
wire    relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_layer11_out_read;
wire   [127:0] relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_layer13_out_din;
wire    relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_layer13_out_write;
wire   [31:0] relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_layer13_out_num_data_valid;
wire   [31:0] relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_layer13_out_fifo_cap;
wire    pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_ap_start;
wire    pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_ap_done;
wire    pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_ap_continue;
wire    pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_ap_idle;
wire    pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_ap_ready;
wire    pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_start_out;
wire    pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_start_write;
wire    pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_layer13_out_read;
wire   [35:0] pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_layer14_out_din;
wire    pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_layer14_out_write;
wire   [31:0] pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_layer14_out_num_data_valid;
wire   [31:0] pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_layer14_out_fifo_cap;
wire    sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_ap_start;
wire    sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_ap_done;
wire    sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_ap_continue;
wire    sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_ap_idle;
wire    sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_ap_ready;
wire    sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_layer14_out_read;
wire   [15:0] sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_layer16_out_TDATA;
wire    sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_layer16_out_TVALID;
wire    layer17_out_full_n;
wire   [15:0] layer17_out_dout;
wire    layer17_out_empty_n;
wire   [10:0] layer17_out_num_data_valid;
wire   [10:0] layer17_out_fifo_cap;
wire    layer2_out_full_n;
wire   [115:0] layer2_out_dout;
wire    layer2_out_empty_n;
wire   [10:0] layer2_out_num_data_valid;
wire   [10:0] layer2_out_fifo_cap;
wire    layer4_out_full_n;
wire   [31:0] layer4_out_dout;
wire    layer4_out_empty_n;
wire   [10:0] layer4_out_num_data_valid;
wire   [10:0] layer4_out_fifo_cap;
wire    layer18_out_full_n;
wire   [31:0] layer18_out_dout;
wire    layer18_out_empty_n;
wire   [10:0] layer18_out_num_data_valid;
wire   [10:0] layer18_out_fifo_cap;
wire    layer5_out_full_n;
wire   [137:0] layer5_out_dout;
wire    layer5_out_empty_n;
wire   [1:0] layer5_out_num_data_valid;
wire   [1:0] layer5_out_fifo_cap;
wire    layer7_out_full_n;
wire   [47:0] layer7_out_dout;
wire    layer7_out_empty_n;
wire   [2:0] layer7_out_num_data_valid;
wire   [2:0] layer7_out_fifo_cap;
wire    layer19_out_full_n;
wire   [47:0] layer19_out_dout;
wire    layer19_out_empty_n;
wire   [7:0] layer19_out_num_data_valid;
wire   [7:0] layer19_out_fifo_cap;
wire    layer8_out_full_n;
wire   [183:0] layer8_out_dout;
wire    layer8_out_empty_n;
wire   [1:0] layer8_out_num_data_valid;
wire   [1:0] layer8_out_fifo_cap;
wire    layer10_out_full_n;
wire   [63:0] layer10_out_dout;
wire    layer10_out_empty_n;
wire   [1:0] layer10_out_num_data_valid;
wire   [1:0] layer10_out_fifo_cap;
wire    layer11_out_full_n;
wire   [223:0] layer11_out_dout;
wire    layer11_out_empty_n;
wire   [1:0] layer11_out_num_data_valid;
wire   [1:0] layer11_out_fifo_cap;
wire    layer13_out_full_n;
wire   [127:0] layer13_out_dout;
wire    layer13_out_empty_n;
wire   [1:0] layer13_out_num_data_valid;
wire   [1:0] layer13_out_fifo_cap;
wire    layer14_out_full_n;
wire   [35:0] layer14_out_dout;
wire    layer14_out_empty_n;
wire   [1:0] layer14_out_num_data_valid;
wire   [1:0] layer14_out_fifo_cap;
wire   [0:0] start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_din;
wire    start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_full_n;
wire   [0:0] start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_dout;
wire    start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_empty_n;
wire   [0:0] start_for_relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_din;
wire    start_for_relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_full_n;
wire   [0:0] start_for_relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_dout;
wire    start_for_relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_empty_n;
wire   [0:0] start_for_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_din;
wire    start_for_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_full_n;
wire   [0:0] start_for_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_dout;
wire    start_for_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_empty_n;
wire   [0:0] start_for_conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_din;
wire    start_for_conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_full_n;
wire   [0:0] start_for_conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_dout;
wire    start_for_conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_empty_n;
wire   [0:0] start_for_relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_din;
wire    start_for_relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_full_n;
wire   [0:0] start_for_relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_dout;
wire    start_for_relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_empty_n;
wire   [0:0] start_for_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_din;
wire    start_for_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_full_n;
wire   [0:0] start_for_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_dout;
wire    start_for_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_empty_n;
wire   [0:0] start_for_conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_din;
wire    start_for_conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_full_n;
wire   [0:0] start_for_conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_dout;
wire    start_for_conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_empty_n;
wire   [0:0] start_for_relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_din;
wire    start_for_relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_full_n;
wire   [0:0] start_for_relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_dout;
wire    start_for_relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_empty_n;
wire   [0:0] start_for_pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_din;
wire    start_for_pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_full_n;
wire   [0:0] start_for_pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_dout;
wire    start_for_pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_empty_n;
wire   [0:0] start_for_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_din;
wire    start_for_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_full_n;
wire   [0:0] start_for_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_dout;
wire    start_for_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_empty_n;
wire   [0:0] start_for_pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_din;
wire    start_for_pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_full_n;
wire   [0:0] start_for_pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_dout;
wire    start_for_pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_empty_n;
wire   [0:0] start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_din;
wire    start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_full_n;
wire   [0:0] start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_dout;
wire    start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_empty_n;

folo_zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_s zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_ap_start),
    .start_full_n(start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_full_n),
    .ap_done(zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_ap_done),
    .ap_continue(zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_ap_continue),
    .ap_idle(zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_ap_idle),
    .ap_ready(zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_ap_ready),
    .start_out(zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_start_out),
    .start_write(zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_start_write),
    .input_3_TDATA(input_3_TDATA),
    .input_3_TVALID(input_3_TVALID),
    .input_3_TREADY(zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_input_3_TREADY),
    .layer17_out_din(zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_layer17_out_din),
    .layer17_out_full_n(layer17_out_full_n),
    .layer17_out_write(zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_layer17_out_write),
    .layer17_out_num_data_valid(zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_layer17_out_num_data_valid),
    .layer17_out_fifo_cap(zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_layer17_out_fifo_cap)
);

folo_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_s conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_ap_start),
    .start_full_n(start_for_relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_full_n),
    .ap_done(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_ap_done),
    .ap_continue(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_ap_continue),
    .ap_idle(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_ap_idle),
    .ap_ready(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_ap_ready),
    .layer17_out_dout(layer17_out_dout),
    .layer17_out_empty_n(layer17_out_empty_n),
    .layer17_out_read(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_layer17_out_read),
    .layer17_out_num_data_valid(layer17_out_num_data_valid),
    .layer17_out_fifo_cap(layer17_out_fifo_cap),
    .start_out(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_start_out),
    .start_write(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_start_write),
    .layer2_out_din(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_layer2_out_din),
    .layer2_out_full_n(layer2_out_full_n),
    .layer2_out_write(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_layer2_out_write),
    .layer2_out_num_data_valid(layer2_out_num_data_valid),
    .layer2_out_fifo_cap(layer2_out_fifo_cap)
);

folo_relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_s relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_ap_start),
    .start_full_n(start_for_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_full_n),
    .ap_done(relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_ap_done),
    .ap_continue(relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_ap_continue),
    .ap_idle(relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_ap_idle),
    .ap_ready(relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_ap_ready),
    .layer2_out_dout(layer2_out_dout),
    .layer2_out_empty_n(layer2_out_empty_n),
    .layer2_out_read(relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_layer2_out_read),
    .layer2_out_num_data_valid(layer2_out_num_data_valid),
    .layer2_out_fifo_cap(layer2_out_fifo_cap),
    .layer4_out_din(relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_layer4_out_din),
    .layer4_out_full_n(layer4_out_full_n),
    .layer4_out_write(relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_layer4_out_write),
    .layer4_out_num_data_valid(relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_layer4_out_num_data_valid),
    .layer4_out_fifo_cap(relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_layer4_out_fifo_cap),
    .start_out(relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_start_out),
    .start_write(relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_start_write)
);

folo_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_s zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_ap_start),
    .start_full_n(start_for_conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_full_n),
    .ap_done(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_ap_done),
    .ap_continue(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_ap_continue),
    .ap_idle(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_ap_idle),
    .ap_ready(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_ap_ready),
    .start_out(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_start_out),
    .start_write(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_start_write),
    .layer4_out_dout(layer4_out_dout),
    .layer4_out_empty_n(layer4_out_empty_n),
    .layer4_out_read(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_layer4_out_read),
    .layer4_out_num_data_valid(layer4_out_num_data_valid),
    .layer4_out_fifo_cap(layer4_out_fifo_cap),
    .layer18_out_din(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_layer18_out_din),
    .layer18_out_full_n(layer18_out_full_n),
    .layer18_out_write(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_layer18_out_write),
    .layer18_out_num_data_valid(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_layer18_out_num_data_valid),
    .layer18_out_fifo_cap(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_layer18_out_fifo_cap)
);

folo_conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_s conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_ap_start),
    .start_full_n(start_for_relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_full_n),
    .ap_done(conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_ap_done),
    .ap_continue(conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_ap_continue),
    .ap_idle(conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_ap_idle),
    .ap_ready(conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_ap_ready),
    .start_out(conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_start_out),
    .start_write(conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_start_write),
    .layer18_out_dout(layer18_out_dout),
    .layer18_out_empty_n(layer18_out_empty_n),
    .layer18_out_read(conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_layer18_out_read),
    .layer18_out_num_data_valid(layer18_out_num_data_valid),
    .layer18_out_fifo_cap(layer18_out_fifo_cap),
    .layer5_out_din(conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_layer5_out_din),
    .layer5_out_full_n(layer5_out_full_n),
    .layer5_out_write(conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_layer5_out_write),
    .layer5_out_num_data_valid(layer5_out_num_data_valid),
    .layer5_out_fifo_cap(layer5_out_fifo_cap)
);

folo_relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_s relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_ap_start),
    .start_full_n(start_for_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_full_n),
    .ap_done(relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_ap_done),
    .ap_continue(relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_ap_continue),
    .ap_idle(relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_ap_idle),
    .ap_ready(relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_ap_ready),
    .layer5_out_dout(layer5_out_dout),
    .layer5_out_empty_n(layer5_out_empty_n),
    .layer5_out_read(relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_layer5_out_read),
    .layer5_out_num_data_valid(layer5_out_num_data_valid),
    .layer5_out_fifo_cap(layer5_out_fifo_cap),
    .layer7_out_din(relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_layer7_out_din),
    .layer7_out_full_n(layer7_out_full_n),
    .layer7_out_write(relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_layer7_out_write),
    .layer7_out_num_data_valid(relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_layer7_out_num_data_valid),
    .layer7_out_fifo_cap(relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_layer7_out_fifo_cap),
    .start_out(relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_start_out),
    .start_write(relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_start_write)
);

folo_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_s zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_ap_start),
    .start_full_n(start_for_conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_full_n),
    .ap_done(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_ap_done),
    .ap_continue(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_ap_continue),
    .ap_idle(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_ap_idle),
    .ap_ready(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_ap_ready),
    .start_out(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_start_out),
    .start_write(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_start_write),
    .layer7_out_dout(layer7_out_dout),
    .layer7_out_empty_n(layer7_out_empty_n),
    .layer7_out_read(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_layer7_out_read),
    .layer7_out_num_data_valid(layer7_out_num_data_valid),
    .layer7_out_fifo_cap(layer7_out_fifo_cap),
    .layer19_out_din(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_layer19_out_din),
    .layer19_out_full_n(layer19_out_full_n),
    .layer19_out_write(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_layer19_out_write),
    .layer19_out_num_data_valid(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_layer19_out_num_data_valid),
    .layer19_out_fifo_cap(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_layer19_out_fifo_cap)
);

folo_conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_s conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_ap_start),
    .start_full_n(start_for_relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_full_n),
    .ap_done(conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_ap_done),
    .ap_continue(conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_ap_continue),
    .ap_idle(conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_ap_idle),
    .ap_ready(conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_ap_ready),
    .start_out(conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_start_out),
    .start_write(conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_start_write),
    .layer19_out_dout(layer19_out_dout),
    .layer19_out_empty_n(layer19_out_empty_n),
    .layer19_out_read(conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_layer19_out_read),
    .layer19_out_num_data_valid(layer19_out_num_data_valid),
    .layer19_out_fifo_cap(layer19_out_fifo_cap),
    .layer8_out_din(conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_layer8_out_din),
    .layer8_out_full_n(layer8_out_full_n),
    .layer8_out_write(conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_layer8_out_write),
    .layer8_out_num_data_valid(layer8_out_num_data_valid),
    .layer8_out_fifo_cap(layer8_out_fifo_cap)
);

folo_relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_s relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_ap_start),
    .start_full_n(start_for_pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_full_n),
    .ap_done(relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_ap_done),
    .ap_continue(relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_ap_continue),
    .ap_idle(relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_ap_idle),
    .ap_ready(relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_ap_ready),
    .layer8_out_dout(layer8_out_dout),
    .layer8_out_empty_n(layer8_out_empty_n),
    .layer8_out_read(relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_layer8_out_read),
    .layer8_out_num_data_valid(layer8_out_num_data_valid),
    .layer8_out_fifo_cap(layer8_out_fifo_cap),
    .layer10_out_din(relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_layer10_out_din),
    .layer10_out_full_n(layer10_out_full_n),
    .layer10_out_write(relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_layer10_out_write),
    .layer10_out_num_data_valid(relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_layer10_out_num_data_valid),
    .layer10_out_fifo_cap(relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_layer10_out_fifo_cap),
    .start_out(relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_start_out),
    .start_write(relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_start_write)
);

folo_pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_s pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_ap_start),
    .start_full_n(start_for_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_full_n),
    .ap_done(pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_ap_done),
    .ap_continue(pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_ap_continue),
    .ap_idle(pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_ap_idle),
    .ap_ready(pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_ap_ready),
    .layer10_out_dout(layer10_out_dout),
    .layer10_out_empty_n(layer10_out_empty_n),
    .layer10_out_read(pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_layer10_out_read),
    .layer10_out_num_data_valid(layer10_out_num_data_valid),
    .layer10_out_fifo_cap(layer10_out_fifo_cap),
    .layer11_out_din(pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_layer11_out_din),
    .layer11_out_full_n(layer11_out_full_n),
    .layer11_out_write(pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_layer11_out_write),
    .layer11_out_num_data_valid(pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_layer11_out_num_data_valid),
    .layer11_out_fifo_cap(pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_layer11_out_fifo_cap),
    .start_out(pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_start_out),
    .start_write(pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_start_write)
);

folo_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_s relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_ap_start),
    .start_full_n(start_for_pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_full_n),
    .ap_done(relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_ap_done),
    .ap_continue(relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_ap_continue),
    .ap_idle(relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_ap_idle),
    .ap_ready(relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_ap_ready),
    .start_out(relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_start_out),
    .start_write(relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_start_write),
    .layer11_out_dout(layer11_out_dout),
    .layer11_out_empty_n(layer11_out_empty_n),
    .layer11_out_read(relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_layer11_out_read),
    .layer11_out_num_data_valid(layer11_out_num_data_valid),
    .layer11_out_fifo_cap(layer11_out_fifo_cap),
    .layer13_out_din(relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_layer13_out_din),
    .layer13_out_full_n(layer13_out_full_n),
    .layer13_out_write(relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_layer13_out_write),
    .layer13_out_num_data_valid(relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_layer13_out_num_data_valid),
    .layer13_out_fifo_cap(relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_layer13_out_fifo_cap)
);

folo_pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_s pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_ap_start),
    .start_full_n(start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_full_n),
    .ap_done(pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_ap_done),
    .ap_continue(pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_ap_continue),
    .ap_idle(pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_ap_idle),
    .ap_ready(pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_ap_ready),
    .start_out(pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_start_out),
    .start_write(pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_start_write),
    .layer13_out_dout(layer13_out_dout),
    .layer13_out_empty_n(layer13_out_empty_n),
    .layer13_out_read(pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_layer13_out_read),
    .layer13_out_num_data_valid(layer13_out_num_data_valid),
    .layer13_out_fifo_cap(layer13_out_fifo_cap),
    .layer14_out_din(pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_layer14_out_din),
    .layer14_out_full_n(layer14_out_full_n),
    .layer14_out_write(pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_layer14_out_write),
    .layer14_out_num_data_valid(pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_layer14_out_num_data_valid),
    .layer14_out_fifo_cap(pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_layer14_out_fifo_cap)
);

folo_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_s sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_ap_start),
    .ap_done(sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_ap_done),
    .ap_continue(sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_ap_continue),
    .ap_idle(sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_ap_idle),
    .ap_ready(sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_ap_ready),
    .layer14_out_dout(layer14_out_dout),
    .layer14_out_empty_n(layer14_out_empty_n),
    .layer14_out_read(sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_layer14_out_read),
    .layer14_out_num_data_valid(layer14_out_num_data_valid),
    .layer14_out_fifo_cap(layer14_out_fifo_cap),
    .layer16_out_TREADY(layer16_out_TREADY),
    .layer16_out_TDATA(sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_layer16_out_TDATA),
    .layer16_out_TVALID(sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_layer16_out_TVALID)
);

folo_fifo_w16_d1000_A layer17_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_layer17_out_din),
    .if_full_n(layer17_out_full_n),
    .if_write(zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_layer17_out_write),
    .if_dout(layer17_out_dout),
    .if_empty_n(layer17_out_empty_n),
    .if_read(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_layer17_out_read),
    .if_num_data_valid(layer17_out_num_data_valid),
    .if_fifo_cap(layer17_out_fifo_cap)
);

folo_fifo_w116_d1000_A layer2_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_layer2_out_din),
    .if_full_n(layer2_out_full_n),
    .if_write(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_layer2_out_write),
    .if_dout(layer2_out_dout),
    .if_empty_n(layer2_out_empty_n),
    .if_read(relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_layer2_out_read),
    .if_num_data_valid(layer2_out_num_data_valid),
    .if_fifo_cap(layer2_out_fifo_cap)
);

folo_fifo_w32_d1000_A layer4_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_layer4_out_din),
    .if_full_n(layer4_out_full_n),
    .if_write(relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_layer4_out_write),
    .if_dout(layer4_out_dout),
    .if_empty_n(layer4_out_empty_n),
    .if_read(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_layer4_out_read),
    .if_num_data_valid(layer4_out_num_data_valid),
    .if_fifo_cap(layer4_out_fifo_cap)
);

folo_fifo_w32_d1000_A layer18_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_layer18_out_din),
    .if_full_n(layer18_out_full_n),
    .if_write(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_layer18_out_write),
    .if_dout(layer18_out_dout),
    .if_empty_n(layer18_out_empty_n),
    .if_read(conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_layer18_out_read),
    .if_num_data_valid(layer18_out_num_data_valid),
    .if_fifo_cap(layer18_out_fifo_cap)
);

folo_fifo_w138_d1_S layer5_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_layer5_out_din),
    .if_full_n(layer5_out_full_n),
    .if_write(conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_layer5_out_write),
    .if_dout(layer5_out_dout),
    .if_empty_n(layer5_out_empty_n),
    .if_read(relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_layer5_out_read),
    .if_num_data_valid(layer5_out_num_data_valid),
    .if_fifo_cap(layer5_out_fifo_cap)
);

folo_fifo_w48_d2_S layer7_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_layer7_out_din),
    .if_full_n(layer7_out_full_n),
    .if_write(relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_layer7_out_write),
    .if_dout(layer7_out_dout),
    .if_empty_n(layer7_out_empty_n),
    .if_read(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_layer7_out_read),
    .if_num_data_valid(layer7_out_num_data_valid),
    .if_fifo_cap(layer7_out_fifo_cap)
);

folo_fifo_w48_d80_A layer19_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_layer19_out_din),
    .if_full_n(layer19_out_full_n),
    .if_write(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_layer19_out_write),
    .if_dout(layer19_out_dout),
    .if_empty_n(layer19_out_empty_n),
    .if_read(conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_layer19_out_read),
    .if_num_data_valid(layer19_out_num_data_valid),
    .if_fifo_cap(layer19_out_fifo_cap)
);

folo_fifo_w184_d1_S layer8_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_layer8_out_din),
    .if_full_n(layer8_out_full_n),
    .if_write(conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_layer8_out_write),
    .if_dout(layer8_out_dout),
    .if_empty_n(layer8_out_empty_n),
    .if_read(relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_layer8_out_read),
    .if_num_data_valid(layer8_out_num_data_valid),
    .if_fifo_cap(layer8_out_fifo_cap)
);

folo_fifo_w64_d1_S layer10_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_layer10_out_din),
    .if_full_n(layer10_out_full_n),
    .if_write(relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_layer10_out_write),
    .if_dout(layer10_out_dout),
    .if_empty_n(layer10_out_empty_n),
    .if_read(pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_layer10_out_read),
    .if_num_data_valid(layer10_out_num_data_valid),
    .if_fifo_cap(layer10_out_fifo_cap)
);

folo_fifo_w224_d1_S layer11_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_layer11_out_din),
    .if_full_n(layer11_out_full_n),
    .if_write(pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_layer11_out_write),
    .if_dout(layer11_out_dout),
    .if_empty_n(layer11_out_empty_n),
    .if_read(relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_layer11_out_read),
    .if_num_data_valid(layer11_out_num_data_valid),
    .if_fifo_cap(layer11_out_fifo_cap)
);

folo_fifo_w128_d1_S layer13_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_layer13_out_din),
    .if_full_n(layer13_out_full_n),
    .if_write(relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_layer13_out_write),
    .if_dout(layer13_out_dout),
    .if_empty_n(layer13_out_empty_n),
    .if_read(pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_layer13_out_read),
    .if_num_data_valid(layer13_out_num_data_valid),
    .if_fifo_cap(layer13_out_fifo_cap)
);

folo_fifo_w36_d1_S layer14_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_layer14_out_din),
    .if_full_n(layer14_out_full_n),
    .if_write(pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_layer14_out_write),
    .if_dout(layer14_out_dout),
    .if_empty_n(layer14_out_empty_n),
    .if_read(sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_layer14_out_read),
    .if_num_data_valid(layer14_out_num_data_valid),
    .if_fifo_cap(layer14_out_fifo_cap)
);

folo_start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0 start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_din),
    .if_full_n(start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_full_n),
    .if_write(zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_start_write),
    .if_dout(start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_dout),
    .if_empty_n(start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_empty_n),
    .if_read(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_ap_ready)
);

folo_start_for_relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0 start_for_relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_din),
    .if_full_n(start_for_relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_full_n),
    .if_write(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_start_write),
    .if_dout(start_for_relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_dout),
    .if_empty_n(start_for_relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_empty_n),
    .if_read(relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_ap_ready)
);

folo_start_for_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0 start_for_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_din),
    .if_full_n(start_for_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_full_n),
    .if_write(relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_start_write),
    .if_dout(start_for_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_dout),
    .if_empty_n(start_for_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_empty_n),
    .if_read(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_ap_ready)
);

folo_start_for_conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0 start_for_conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_din),
    .if_full_n(start_for_conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_full_n),
    .if_write(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_start_write),
    .if_dout(start_for_conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_dout),
    .if_empty_n(start_for_conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_empty_n),
    .if_read(conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_ap_ready)
);

folo_start_for_relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0 start_for_relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_din),
    .if_full_n(start_for_relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_full_n),
    .if_write(conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_start_write),
    .if_dout(start_for_relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_dout),
    .if_empty_n(start_for_relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_empty_n),
    .if_read(relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_ap_ready)
);

folo_start_for_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0 start_for_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_din),
    .if_full_n(start_for_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_full_n),
    .if_write(relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_start_write),
    .if_dout(start_for_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_dout),
    .if_empty_n(start_for_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_empty_n),
    .if_read(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_ap_ready)
);

folo_start_for_conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0 start_for_conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_din),
    .if_full_n(start_for_conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_full_n),
    .if_write(zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_start_write),
    .if_dout(start_for_conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_dout),
    .if_empty_n(start_for_conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_empty_n),
    .if_read(conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_ap_ready)
);

folo_start_for_relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0 start_for_relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_din),
    .if_full_n(start_for_relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_full_n),
    .if_write(conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_start_write),
    .if_dout(start_for_relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_dout),
    .if_empty_n(start_for_relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_empty_n),
    .if_read(relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_ap_ready)
);

folo_start_for_pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0 start_for_pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_din),
    .if_full_n(start_for_pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_full_n),
    .if_write(relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_start_write),
    .if_dout(start_for_pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_dout),
    .if_empty_n(start_for_pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_empty_n),
    .if_read(pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_ap_ready)
);

folo_start_for_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0 start_for_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_din),
    .if_full_n(start_for_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_full_n),
    .if_write(pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_start_write),
    .if_dout(start_for_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_dout),
    .if_empty_n(start_for_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_empty_n),
    .if_read(relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_ap_ready)
);

folo_start_for_pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0 start_for_pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_din),
    .if_full_n(start_for_pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_full_n),
    .if_write(relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_start_write),
    .if_dout(start_for_pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_dout),
    .if_empty_n(start_for_pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_empty_n),
    .if_read(pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_ap_ready)
);

folo_start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0 start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_din),
    .if_full_n(start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_full_n),
    .if_write(pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_start_write),
    .if_dout(start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_dout),
    .if_empty_n(start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_empty_n),
    .if_read(sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_ap_ready)
);

assign ap_done = sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_ap_done;

assign ap_idle = (zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_ap_idle & zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_ap_idle & zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_ap_idle & sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_ap_idle & relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_ap_idle & relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_ap_idle & relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_ap_idle & relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_ap_idle & pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_ap_idle & pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_ap_idle & conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_ap_idle & conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_ap_idle & conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_ap_idle);

assign ap_ready = zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_ap_continue = 1'b1;

assign conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_ap_start = start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_empty_n;

assign conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_ap_continue = 1'b1;

assign conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_ap_start = start_for_conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_empty_n;

assign conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_ap_continue = 1'b1;

assign conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_ap_start = start_for_conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_empty_n;

assign input_3_TREADY = zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_input_3_TREADY;

assign layer16_out_TDATA = sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_layer16_out_TDATA;

assign layer16_out_TVALID = sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_layer16_out_TVALID;

assign pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_ap_continue = 1'b1;

assign pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_ap_start = start_for_pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_empty_n;

assign pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_layer11_out_fifo_cap = layer11_out_fifo_cap;

assign pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_layer11_out_num_data_valid = layer11_out_num_data_valid;

assign pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_ap_continue = 1'b1;

assign pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_ap_start = start_for_pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_empty_n;

assign pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_layer14_out_fifo_cap = layer14_out_fifo_cap;

assign pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_layer14_out_num_data_valid = layer14_out_num_data_valid;

assign relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_ap_continue = 1'b1;

assign relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_ap_start = start_for_relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_empty_n;

assign relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_layer4_out_fifo_cap = layer4_out_fifo_cap;

assign relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_layer4_out_num_data_valid = layer4_out_num_data_valid;

assign relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_ap_continue = 1'b1;

assign relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_ap_start = start_for_relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_empty_n;

assign relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_layer7_out_fifo_cap = layer7_out_fifo_cap;

assign relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_layer7_out_num_data_valid = layer7_out_num_data_valid;

assign relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_ap_continue = 1'b1;

assign relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_ap_start = start_for_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_empty_n;

assign relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_layer13_out_fifo_cap = layer13_out_fifo_cap;

assign relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_layer13_out_num_data_valid = layer13_out_num_data_valid;

assign relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_ap_continue = 1'b1;

assign relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_ap_start = start_for_relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_empty_n;

assign relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_layer10_out_fifo_cap = layer10_out_fifo_cap;

assign relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_layer10_out_num_data_valid = layer10_out_num_data_valid;

assign sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_ap_continue = 1'b1;

assign sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_ap_start = start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_empty_n;

assign start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_29_12_5_3_0_4u_config2_U0_din = 1'b1;

assign start_for_conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_23_8_5_3_0_6u_config5_U0_din = 1'b1;

assign start_for_conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_23_8_5_3_0_8u_config8_U0_din = 1'b1;

assign start_for_pointwise_conv_2d_cl_array_array_ap_fixed_28_10_5_3_0_8u_config20_U0_din = 1'b1;

assign start_for_pointwise_conv_2d_cl_array_array_ap_fixed_36_16_5_3_0_1u_config21_U0_din = 1'b1;

assign start_for_relu_array_ap_fixed_4u_array_ap_ufixed_8_0_4_0_0_4u_relu_config4_U0_din = 1'b1;

assign start_for_relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config7_U0_din = 1'b1;

assign start_for_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config13_U0_din = 1'b1;

assign start_for_relu_array_ap_fixed_8u_array_ap_ufixed_8_0_4_0_0_8u_relu_config10_U0_din = 1'b1;

assign start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config16_U0_din = 1'b1;

assign start_for_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_din = 1'b1;

assign start_for_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_din = 1'b1;

assign zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_ap_continue = 1'b1;

assign zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_ap_start = ap_start;

assign zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_layer17_out_fifo_cap = layer17_out_fifo_cap;

assign zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_1u_config17_U0_layer17_out_num_data_valid = layer17_out_num_data_valid;

assign zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_ap_continue = 1'b1;

assign zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_ap_start = start_for_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_empty_n;

assign zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_layer18_out_fifo_cap = layer18_out_fifo_cap;

assign zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_4u_config18_U0_layer18_out_num_data_valid = layer18_out_num_data_valid;

assign zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_ap_continue = 1'b1;

assign zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_ap_start = start_for_zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_empty_n;

assign zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_layer19_out_fifo_cap = layer19_out_fifo_cap;

assign zeropad2d_cl_array_array_ap_ufixed_8_0_4_0_0_6u_config19_U0_layer19_out_num_data_valid = layer19_out_num_data_valid;


reg find_df_deadlock = 0;
// synthesis translate_off
`include "folo_hls_deadlock_detector.vh"
// synthesis translate_on

reg find_kernel_block = 0;
// synthesis translate_off
`include "folo_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //folo

