// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module gaussian_dense_array_ap_ufixed_16u_array_ap_fixed_29_11_5_3_0_1u_config24_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer33_cpy4_dout,
        layer33_cpy4_empty_n,
        layer33_cpy4_read,
        layer33_cpy4_num_data_valid,
        layer33_cpy4_fifo_cap,
        layer24_out_din,
        layer24_out_full_n,
        layer24_out_write,
        layer24_out_num_data_valid,
        layer24_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 13'd1;
parameter    ap_ST_fsm_state2 = 13'd2;
parameter    ap_ST_fsm_state3 = 13'd4;
parameter    ap_ST_fsm_state4 = 13'd8;
parameter    ap_ST_fsm_state5 = 13'd16;
parameter    ap_ST_fsm_state6 = 13'd32;
parameter    ap_ST_fsm_state7 = 13'd64;
parameter    ap_ST_fsm_state8 = 13'd128;
parameter    ap_ST_fsm_state9 = 13'd256;
parameter    ap_ST_fsm_state10 = 13'd512;
parameter    ap_ST_fsm_state11 = 13'd1024;
parameter    ap_ST_fsm_state12 = 13'd2048;
parameter    ap_ST_fsm_state13 = 13'd4096;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [127:0] layer33_cpy4_dout;
input   layer33_cpy4_empty_n;
output   layer33_cpy4_read;
input  [1:0] layer33_cpy4_num_data_valid;
input  [1:0] layer33_cpy4_fifo_cap;
output  [28:0] layer24_out_din;
input   layer24_out_full_n;
output   layer24_out_write;
input  [1:0] layer24_out_num_data_valid;
input  [1:0] layer24_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer33_cpy4_read;
reg layer24_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [12:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer33_cpy4_blk_n;
reg    layer24_out_blk_n;
wire    ap_CS_fsm_state13;
wire   [7:0] data_fu_115_p1;
reg   [7:0] data_reg_273;
reg    ap_block_state1;
reg   [7:0] data_57_reg_278;
reg   [7:0] data_43_reg_283;
reg   [7:0] data_44_reg_288;
reg   [7:0] data_45_reg_293;
reg   [7:0] data_46_reg_298;
reg   [7:0] data_47_reg_303;
reg   [7:0] data_48_reg_308;
reg   [7:0] data_49_reg_313;
reg   [7:0] data_50_reg_318;
reg   [7:0] data_51_reg_323;
reg   [7:0] data_52_reg_328;
reg   [7:0] data_53_reg_333;
reg   [7:0] data_54_reg_338;
reg   [7:0] data_55_reg_343;
reg   [7:0] data_56_reg_348;
wire   [21:0] grp_dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_29_11_5_3_0_config24_s_fu_95_ap_return;
reg   [21:0] res_reg_353;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state2;
reg   [12:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 13'd1;
end

gaussian_dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_29_11_5_3_0_config24_s grp_dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_29_11_5_3_0_config24_s_fu_95(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_0_val(data_reg_273),
    .data_1_val(data_57_reg_278),
    .data_2_val(data_43_reg_283),
    .data_3_val(data_44_reg_288),
    .data_4_val(data_45_reg_293),
    .data_5_val(data_46_reg_298),
    .data_6_val(data_47_reg_303),
    .data_7_val(data_48_reg_308),
    .data_8_val(data_49_reg_313),
    .data_9_val(data_50_reg_318),
    .data_10_val(data_51_reg_323),
    .data_11_val(data_52_reg_328),
    .data_12_val(data_53_reg_333),
    .data_13_val(data_54_reg_338),
    .data_14_val(data_55_reg_343),
    .data_15_val(data_56_reg_348),
    .ap_return(grp_dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_29_11_5_3_0_config24_s_fu_95_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((layer24_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        data_43_reg_283 <= {{layer33_cpy4_dout[23:16]}};
        data_44_reg_288 <= {{layer33_cpy4_dout[31:24]}};
        data_45_reg_293 <= {{layer33_cpy4_dout[39:32]}};
        data_46_reg_298 <= {{layer33_cpy4_dout[47:40]}};
        data_47_reg_303 <= {{layer33_cpy4_dout[55:48]}};
        data_48_reg_308 <= {{layer33_cpy4_dout[63:56]}};
        data_49_reg_313 <= {{layer33_cpy4_dout[71:64]}};
        data_50_reg_318 <= {{layer33_cpy4_dout[79:72]}};
        data_51_reg_323 <= {{layer33_cpy4_dout[87:80]}};
        data_52_reg_328 <= {{layer33_cpy4_dout[95:88]}};
        data_53_reg_333 <= {{layer33_cpy4_dout[103:96]}};
        data_54_reg_338 <= {{layer33_cpy4_dout[111:104]}};
        data_55_reg_343 <= {{layer33_cpy4_dout[119:112]}};
        data_56_reg_348 <= {{layer33_cpy4_dout[127:120]}};
        data_57_reg_278 <= {{layer33_cpy4_dout[15:8]}};
        data_reg_273 <= data_fu_115_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        res_reg_353 <= grp_dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_29_11_5_3_0_config24_s_fu_95_ap_return;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((layer24_out_full_n == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((layer24_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((layer24_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        layer24_out_blk_n = layer24_out_full_n;
    end else begin
        layer24_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer24_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        layer24_out_write = 1'b1;
    end else begin
        layer24_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer33_cpy4_blk_n = layer33_cpy4_empty_n;
    end else begin
        layer33_cpy4_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer33_cpy4_read = 1'b1;
    end else begin
        layer33_cpy4_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((layer24_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((layer33_cpy4_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign data_fu_115_p1 = layer33_cpy4_dout[7:0];

assign layer24_out_din = $signed(res_reg_353);

assign start_out = real_start;

endmodule //gaussian_dense_array_ap_ufixed_16u_array_ap_fixed_29_11_5_3_0_1u_config24_s
