// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module gaussian_sigmoid_array_array_ap_fixed_16_6_5_3_0_2u_sigmoid_config26_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer18_out_dout,
        layer18_out_empty_n,
        layer18_out_read,
        layer18_out_num_data_valid,
        layer18_out_fifo_cap,
        layer26_out_din,
        layer26_out_full_n,
        layer26_out_write,
        layer26_out_num_data_valid,
        layer26_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [57:0] layer18_out_dout;
input   layer18_out_empty_n;
output   layer18_out_read;
input  [1:0] layer18_out_num_data_valid;
input  [1:0] layer18_out_fifo_cap;
output  [31:0] layer26_out_din;
input   layer26_out_full_n;
output   layer26_out_write;
input  [1:0] layer26_out_num_data_valid;
input  [1:0] layer26_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer18_out_read;
reg layer26_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
wire   [9:0] sigmoid_table_address0;
wire   [9:0] sigmoid_table_q0;
wire   [9:0] sigmoid_table_address1;
wire   [9:0] sigmoid_table_q1;
reg    layer18_out_blk_n;
reg    layer26_out_blk_n;
wire    ap_CS_fsm_state7;
reg   [57:0] layer18_out_read_reg_365;
reg    ap_block_state1;
reg   [16:0] tmp_reg_371;
wire   [11:0] trunc_ln90_fu_118_p1;
reg   [11:0] trunc_ln90_reg_376;
reg   [16:0] tmp_6_reg_381;
reg   [11:0] tmp_8_reg_388;
wire  signed [17:0] sext_ln90_fu_142_p1;
reg  signed [17:0] sext_ln90_reg_393;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln90_fu_152_p2;
reg   [0:0] icmp_ln90_reg_399;
wire   [17:0] add_ln90_fu_158_p2;
reg   [17:0] add_ln90_reg_404;
wire   [0:0] icmp_ln90_1_fu_171_p2;
reg   [0:0] icmp_ln90_1_reg_409;
wire   [16:0] add_ln90_1_fu_177_p2;
reg   [16:0] add_ln90_1_reg_414;
wire   [17:0] index_fu_201_p2;
reg   [17:0] index_reg_419;
wire    ap_CS_fsm_state3;
reg   [0:0] tmp_19_reg_424;
reg   [7:0] tmp_20_reg_430;
wire   [17:0] index_8_fu_248_p2;
reg   [17:0] index_8_reg_435;
reg   [0:0] tmp_22_reg_440;
reg   [7:0] tmp_23_reg_446;
wire   [9:0] index_7_fu_298_p3;
reg   [9:0] index_7_reg_451;
wire    ap_CS_fsm_state4;
wire   [9:0] index_9_fu_332_p3;
reg   [9:0] index_9_reg_456;
wire    ap_CS_fsm_state5;
wire   [63:0] zext_ln96_fu_340_p1;
wire   [63:0] zext_ln96_1_fu_344_p1;
reg    sigmoid_table_ce1_local;
wire    ap_CS_fsm_state6;
reg    sigmoid_table_ce0_local;
wire   [17:0] tmp_5_fu_145_p3;
wire   [17:0] tmp_9_fu_164_p3;
wire   [0:0] tmp_18_fu_182_p3;
wire   [17:0] select_ln90_fu_189_p3;
wire   [17:0] data_round_fu_194_p3;
wire   [0:0] tmp_21_fu_225_p3;
wire   [16:0] select_ln90_1_fu_232_p3;
wire   [16:0] data_round_3_fu_237_p3;
wire  signed [17:0] sext_ln90_1_fu_244_p1;
wire   [0:0] xor_ln92_fu_280_p2;
wire   [0:0] icmp_ln94_fu_275_p2;
wire   [0:0] or_ln92_fu_293_p2;
wire   [9:0] select_ln92_fu_285_p3;
wire   [9:0] trunc_ln91_fu_272_p1;
wire   [0:0] xor_ln92_1_fu_314_p2;
wire   [0:0] icmp_ln94_1_fu_309_p2;
wire   [0:0] or_ln92_1_fu_327_p2;
wire   [9:0] select_ln92_2_fu_319_p3;
wire   [9:0] trunc_ln91_1_fu_306_p1;
wire   [15:0] zext_ln96_2_fu_348_p1;
wire   [25:0] tmp_1_fu_352_p3;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 7'd1;
end

gaussian_sigmoid_array_array_ap_fixed_16_6_5_3_0_2u_sigmoid_config26_s_sigmoid_table_RFfa #(
    .DataWidth( 10 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
sigmoid_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sigmoid_table_address0),
    .ce0(sigmoid_table_ce0_local),
    .q0(sigmoid_table_q0),
    .address1(sigmoid_table_address1),
    .ce1(sigmoid_table_ce1_local),
    .q1(sigmoid_table_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((layer26_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln90_1_reg_414 <= add_ln90_1_fu_177_p2;
        add_ln90_reg_404 <= add_ln90_fu_158_p2;
        icmp_ln90_1_reg_409 <= icmp_ln90_1_fu_171_p2;
        icmp_ln90_reg_399 <= icmp_ln90_fu_152_p2;
        sext_ln90_reg_393 <= sext_ln90_fu_142_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        index_7_reg_451 <= index_7_fu_298_p3;
        index_9_reg_456 <= index_9_fu_332_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        index_8_reg_435 <= index_8_fu_248_p2;
        index_reg_419 <= index_fu_201_p2;
        tmp_19_reg_424 <= index_fu_201_p2[32'd17];
        tmp_20_reg_430 <= {{index_fu_201_p2[17:10]}};
        tmp_22_reg_440 <= index_8_fu_248_p2[32'd17];
        tmp_23_reg_446 <= {{index_8_fu_248_p2[17:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer18_out_read_reg_365 <= layer18_out_dout;
        tmp_6_reg_381 <= {{layer18_out_dout[57:41]}};
        tmp_8_reg_388 <= {{layer18_out_dout[40:29]}};
        tmp_reg_371 <= {{layer18_out_dout[28:12]}};
        trunc_ln90_reg_376 <= trunc_ln90_fu_118_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((layer26_out_full_n == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer26_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((layer26_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer18_out_blk_n = layer18_out_empty_n;
    end else begin
        layer18_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer18_out_read = 1'b1;
    end else begin
        layer18_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        layer26_out_blk_n = layer26_out_full_n;
    end else begin
        layer26_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer26_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        layer26_out_write = 1'b1;
    end else begin
        layer26_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        sigmoid_table_ce0_local = 1'b1;
    end else begin
        sigmoid_table_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        sigmoid_table_ce1_local = 1'b1;
    end else begin
        sigmoid_table_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((layer26_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln90_1_fu_177_p2 = (tmp_6_reg_381 + 17'd1);

assign add_ln90_fu_158_p2 = ($signed(sext_ln90_fu_142_p1) + $signed(18'd1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_block_state1 = ((layer18_out_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign data_round_3_fu_237_p3 = ((tmp_21_fu_225_p3[0:0] == 1'b1) ? select_ln90_1_fu_232_p3 : tmp_6_reg_381);

assign data_round_fu_194_p3 = ((tmp_18_fu_182_p3[0:0] == 1'b1) ? select_ln90_fu_189_p3 : sext_ln90_reg_393);

assign icmp_ln90_1_fu_171_p2 = ((tmp_9_fu_164_p3 != 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln90_fu_152_p2 = ((tmp_5_fu_145_p3 != 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln94_1_fu_309_p2 = ((tmp_23_reg_446 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln94_fu_275_p2 = ((tmp_20_reg_430 != 8'd0) ? 1'b1 : 1'b0);

assign index_7_fu_298_p3 = ((or_ln92_fu_293_p2[0:0] == 1'b1) ? select_ln92_fu_285_p3 : trunc_ln91_fu_272_p1);

assign index_8_fu_248_p2 = ($signed(sext_ln90_1_fu_244_p1) + $signed(18'd512));

assign index_9_fu_332_p3 = ((or_ln92_1_fu_327_p2[0:0] == 1'b1) ? select_ln92_2_fu_319_p3 : trunc_ln91_1_fu_306_p1);

assign index_fu_201_p2 = (data_round_fu_194_p3 + 18'd512);

assign layer26_out_din = tmp_1_fu_352_p3;

assign or_ln92_1_fu_327_p2 = (tmp_22_reg_440 | icmp_ln94_1_fu_309_p2);

assign or_ln92_fu_293_p2 = (tmp_19_reg_424 | icmp_ln94_fu_275_p2);

assign select_ln90_1_fu_232_p3 = ((icmp_ln90_1_reg_409[0:0] == 1'b1) ? add_ln90_1_reg_414 : tmp_6_reg_381);

assign select_ln90_fu_189_p3 = ((icmp_ln90_reg_399[0:0] == 1'b1) ? add_ln90_reg_404 : sext_ln90_reg_393);

assign select_ln92_2_fu_319_p3 = ((xor_ln92_1_fu_314_p2[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign select_ln92_fu_285_p3 = ((xor_ln92_fu_280_p2[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign sext_ln90_1_fu_244_p1 = $signed(data_round_3_fu_237_p3);

assign sext_ln90_fu_142_p1 = $signed(tmp_reg_371);

assign sigmoid_table_address0 = zext_ln96_1_fu_344_p1;

assign sigmoid_table_address1 = zext_ln96_fu_340_p1;

assign start_out = real_start;

assign tmp_18_fu_182_p3 = layer18_out_read_reg_365[32'd28];

assign tmp_1_fu_352_p3 = {{sigmoid_table_q0}, {zext_ln96_2_fu_348_p1}};

assign tmp_21_fu_225_p3 = layer18_out_read_reg_365[32'd57];

assign tmp_5_fu_145_p3 = {{trunc_ln90_reg_376}, {6'd0}};

assign tmp_9_fu_164_p3 = {{tmp_8_reg_388}, {6'd0}};

assign trunc_ln90_fu_118_p1 = layer18_out_dout[11:0];

assign trunc_ln91_1_fu_306_p1 = index_8_reg_435[9:0];

assign trunc_ln91_fu_272_p1 = index_reg_419[9:0];

assign xor_ln92_1_fu_314_p2 = (tmp_22_reg_440 ^ 1'd1);

assign xor_ln92_fu_280_p2 = (tmp_19_reg_424 ^ 1'd1);

assign zext_ln96_1_fu_344_p1 = index_9_reg_456;

assign zext_ln96_2_fu_348_p1 = sigmoid_table_q1;

assign zext_ln96_fu_340_p1 = index_7_reg_451;

endmodule //gaussian_sigmoid_array_array_ap_fixed_16_6_5_3_0_2u_sigmoid_config26_s
