-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity gaussian_global_pooling2d_cl_array_array_ap_fixed_16_6_5_3_0_8u_config14_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    layer13_out_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    layer13_out_empty_n : IN STD_LOGIC;
    layer13_out_read : OUT STD_LOGIC;
    layer13_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer13_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer14_out_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    layer14_out_full_n : IN STD_LOGIC;
    layer14_out_write : OUT STD_LOGIC;
    layer14_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer14_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of gaussian_global_pooling2d_cl_array_array_ap_fixed_16_6_5_3_0_8u_config14_s is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv54_1C71C71C8 : STD_LOGIC_VECTOR (53 downto 0) := "000000000000000000000111000111000111000111000111001000";
    constant ap_const_lv32_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100110";
    constant ap_const_lv32_35 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110101";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal layer14_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal trunc_ln_reg_414 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal trunc_ln279_1_reg_419 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln279_2_reg_424 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln279_3_reg_429 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln279_4_reg_434 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln279_5_reg_439 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln279_6_reg_444 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln279_7_reg_449 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_ap_start : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_ap_done : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_ap_idle : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_ap_ready : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_layer13_out_read : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_1_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_2_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_2_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_3_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_3_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_4_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_4_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_5_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_5_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_6_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_6_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_7_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_7_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call10 : BOOLEAN;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_fu_85_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_85_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_90_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_90_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_95_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_95_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_100_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_100_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_105_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_105_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_110_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_110_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_115_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_115_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_120_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_120_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln279_fu_161_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln279_1_fu_170_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln279_2_fu_179_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln279_3_fu_188_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln279_4_fu_197_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln279_5_fu_206_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln279_6_fu_215_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln279_7_fu_224_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_85_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal grp_fu_90_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal grp_fu_95_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal grp_fu_100_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal grp_fu_105_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal grp_fu_110_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal grp_fu_115_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal grp_fu_120_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal grp_fu_100_p00 : STD_LOGIC_VECTOR (53 downto 0);
    signal grp_fu_105_p00 : STD_LOGIC_VECTOR (53 downto 0);
    signal grp_fu_110_p00 : STD_LOGIC_VECTOR (53 downto 0);
    signal grp_fu_115_p00 : STD_LOGIC_VECTOR (53 downto 0);
    signal grp_fu_120_p00 : STD_LOGIC_VECTOR (53 downto 0);
    signal grp_fu_85_p00 : STD_LOGIC_VECTOR (53 downto 0);
    signal grp_fu_90_p00 : STD_LOGIC_VECTOR (53 downto 0);
    signal grp_fu_95_p00 : STD_LOGIC_VECTOR (53 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component gaussian_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        layer13_out_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        layer13_out_empty_n : IN STD_LOGIC;
        layer13_out_read : OUT STD_LOGIC;
        layer13_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        layer13_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        data_window_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_out_ap_vld : OUT STD_LOGIC;
        data_window_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_1_out_ap_vld : OUT STD_LOGIC;
        data_window_2_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_2_out_ap_vld : OUT STD_LOGIC;
        data_window_3_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_3_out_ap_vld : OUT STD_LOGIC;
        data_window_4_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_4_out_ap_vld : OUT STD_LOGIC;
        data_window_5_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_5_out_ap_vld : OUT STD_LOGIC;
        data_window_6_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_6_out_ap_vld : OUT STD_LOGIC;
        data_window_7_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_7_out_ap_vld : OUT STD_LOGIC );
    end component;


    component gaussian_mul_32ns_34ns_54_5_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (33 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (53 downto 0) );
    end component;



begin
    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71 : component gaussian_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_ap_start,
        ap_done => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_ap_done,
        ap_idle => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_ap_idle,
        ap_ready => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_ap_ready,
        layer13_out_dout => layer13_out_dout,
        layer13_out_empty_n => layer13_out_empty_n,
        layer13_out_read => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_layer13_out_read,
        layer13_out_num_data_valid => ap_const_lv2_0,
        layer13_out_fifo_cap => ap_const_lv2_0,
        data_window_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_out,
        data_window_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_out_ap_vld,
        data_window_1_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_1_out,
        data_window_1_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_1_out_ap_vld,
        data_window_2_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_2_out,
        data_window_2_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_2_out_ap_vld,
        data_window_3_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_3_out,
        data_window_3_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_3_out_ap_vld,
        data_window_4_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_4_out,
        data_window_4_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_4_out_ap_vld,
        data_window_5_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_5_out,
        data_window_5_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_5_out_ap_vld,
        data_window_6_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_6_out,
        data_window_6_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_6_out_ap_vld,
        data_window_7_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_7_out,
        data_window_7_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_7_out_ap_vld);

    mul_32ns_34ns_54_5_1_U758 : component gaussian_mul_32ns_34ns_54_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 34,
        dout_WIDTH => 54)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_85_p0,
        din1 => grp_fu_85_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_85_p2);

    mul_32ns_34ns_54_5_1_U759 : component gaussian_mul_32ns_34ns_54_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 34,
        dout_WIDTH => 54)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_90_p0,
        din1 => grp_fu_90_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_90_p2);

    mul_32ns_34ns_54_5_1_U760 : component gaussian_mul_32ns_34ns_54_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 34,
        dout_WIDTH => 54)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_95_p0,
        din1 => grp_fu_95_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_95_p2);

    mul_32ns_34ns_54_5_1_U761 : component gaussian_mul_32ns_34ns_54_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 34,
        dout_WIDTH => 54)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_100_p0,
        din1 => grp_fu_100_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_100_p2);

    mul_32ns_34ns_54_5_1_U762 : component gaussian_mul_32ns_34ns_54_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 34,
        dout_WIDTH => 54)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_105_p0,
        din1 => grp_fu_105_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_105_p2);

    mul_32ns_34ns_54_5_1_U763 : component gaussian_mul_32ns_34ns_54_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 34,
        dout_WIDTH => 54)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_110_p0,
        din1 => grp_fu_110_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_110_p2);

    mul_32ns_34ns_54_5_1_U764 : component gaussian_mul_32ns_34ns_54_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 34,
        dout_WIDTH => 54)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_115_p0,
        din1 => grp_fu_115_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_115_p2);

    mul_32ns_34ns_54_5_1_U765 : component gaussian_mul_32ns_34ns_54_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 34,
        dout_WIDTH => 54)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_120_p0,
        din1 => grp_fu_120_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_120_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((layer14_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1_ignore_call10))) then 
                    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_ap_ready = ap_const_logic_1)) then 
                    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                trunc_ln279_1_reg_419 <= grp_fu_90_p2(53 downto 38);
                trunc_ln279_2_reg_424 <= grp_fu_95_p2(53 downto 38);
                trunc_ln279_3_reg_429 <= grp_fu_100_p2(53 downto 38);
                trunc_ln279_4_reg_434 <= grp_fu_105_p2(53 downto 38);
                trunc_ln279_5_reg_439 <= grp_fu_110_p2(53 downto 38);
                trunc_ln279_6_reg_444 <= grp_fu_115_p2(53 downto 38);
                trunc_ln279_7_reg_449 <= grp_fu_120_p2(53 downto 38);
                trunc_ln_reg_414 <= grp_fu_85_p2(53 downto 38);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, layer14_out_full_n, ap_CS_fsm_state8, grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_ap_done, ap_CS_fsm_state2, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((layer14_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_ap_done)
    begin
        if ((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(layer14_out_full_n)
    begin
        if ((layer14_out_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state1_ignore_call10_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call10 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, layer14_out_full_n, ap_CS_fsm_state8)
    begin
        if (((layer14_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    grp_fu_100_p0 <= grp_fu_100_p00(32 - 1 downto 0);
    grp_fu_100_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln279_3_fu_188_p1),54));
    grp_fu_100_p1 <= ap_const_lv54_1C71C71C8(34 - 1 downto 0);
    grp_fu_105_p0 <= grp_fu_105_p00(32 - 1 downto 0);
    grp_fu_105_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln279_4_fu_197_p1),54));
    grp_fu_105_p1 <= ap_const_lv54_1C71C71C8(34 - 1 downto 0);
    grp_fu_110_p0 <= grp_fu_110_p00(32 - 1 downto 0);
    grp_fu_110_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln279_5_fu_206_p1),54));
    grp_fu_110_p1 <= ap_const_lv54_1C71C71C8(34 - 1 downto 0);
    grp_fu_115_p0 <= grp_fu_115_p00(32 - 1 downto 0);
    grp_fu_115_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln279_6_fu_215_p1),54));
    grp_fu_115_p1 <= ap_const_lv54_1C71C71C8(34 - 1 downto 0);
    grp_fu_120_p0 <= grp_fu_120_p00(32 - 1 downto 0);
    grp_fu_120_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln279_7_fu_224_p1),54));
    grp_fu_120_p1 <= ap_const_lv54_1C71C71C8(34 - 1 downto 0);
    grp_fu_85_p0 <= grp_fu_85_p00(32 - 1 downto 0);
    grp_fu_85_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln279_fu_161_p1),54));
    grp_fu_85_p1 <= ap_const_lv54_1C71C71C8(34 - 1 downto 0);
    grp_fu_90_p0 <= grp_fu_90_p00(32 - 1 downto 0);
    grp_fu_90_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln279_1_fu_170_p1),54));
    grp_fu_90_p1 <= ap_const_lv54_1C71C71C8(34 - 1 downto 0);
    grp_fu_95_p0 <= grp_fu_95_p00(32 - 1 downto 0);
    grp_fu_95_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln279_2_fu_179_p1),54));
    grp_fu_95_p1 <= ap_const_lv54_1C71C71C8(34 - 1 downto 0);
    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_ap_start <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_ap_start_reg;

    internal_ap_ready_assign_proc : process(layer14_out_full_n, ap_CS_fsm_state8)
    begin
        if (((layer14_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    layer13_out_read <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_layer13_out_read;

    layer14_out_blk_n_assign_proc : process(layer14_out_full_n, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            layer14_out_blk_n <= layer14_out_full_n;
        else 
            layer14_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer14_out_din <= (((((((trunc_ln279_7_reg_449 & trunc_ln279_6_reg_444) & trunc_ln279_5_reg_439) & trunc_ln279_4_reg_434) & trunc_ln279_3_reg_429) & trunc_ln279_2_reg_424) & trunc_ln279_1_reg_419) & trunc_ln_reg_414);

    layer14_out_write_assign_proc : process(layer14_out_full_n, ap_CS_fsm_state8)
    begin
        if (((layer14_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            layer14_out_write <= ap_const_logic_1;
        else 
            layer14_out_write <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

        sext_ln279_1_fu_170_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_1_out),32));

        sext_ln279_2_fu_179_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_2_out),32));

        sext_ln279_3_fu_188_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_3_out),32));

        sext_ln279_4_fu_197_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_4_out),32));

        sext_ln279_5_fu_206_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_5_out),32));

        sext_ln279_6_fu_215_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_6_out),32));

        sext_ln279_7_fu_224_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_7_out),32));

        sext_ln279_fu_161_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_71_data_window_out),32));

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
