-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity gaussian_dense_array_ap_ufixed_16u_array_ap_fixed_29_11_5_3_0_1u_config24_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    layer33_cpy4_dout : IN STD_LOGIC_VECTOR (127 downto 0);
    layer33_cpy4_empty_n : IN STD_LOGIC;
    layer33_cpy4_read : OUT STD_LOGIC;
    layer33_cpy4_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer33_cpy4_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer24_out_din : OUT STD_LOGIC_VECTOR (28 downto 0);
    layer24_out_full_n : IN STD_LOGIC;
    layer24_out_write : OUT STD_LOGIC;
    layer24_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer24_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of gaussian_dense_array_ap_ufixed_16u_array_ap_fixed_29_11_5_3_0_1u_config24_s is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (12 downto 0) := "0000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (12 downto 0) := "0000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (12 downto 0) := "0000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (12 downto 0) := "0000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (12 downto 0) := "0000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (12 downto 0) := "0000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (12 downto 0) := "0001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (12 downto 0) := "0010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (12 downto 0) := "0100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";
    constant ap_const_lv32_48 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_57 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010111";
    constant ap_const_lv32_58 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_67 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100111";
    constant ap_const_lv32_68 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_77 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110111";
    constant ap_const_lv32_78 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal layer33_cpy4_blk_n : STD_LOGIC;
    signal layer24_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal data_fu_115_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_reg_273 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal data_57_reg_278 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_43_reg_283 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_44_reg_288 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_45_reg_293 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_46_reg_298 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_47_reg_303 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_48_reg_308 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_49_reg_313 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_50_reg_318 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_51_reg_323 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_52_reg_328 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_53_reg_333 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_54_reg_338 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_55_reg_343 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_56_reg_348 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_29_11_5_3_0_config24_s_fu_95_ap_return : STD_LOGIC_VECTOR (21 downto 0);
    signal res_reg_353 : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component gaussian_dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_29_11_5_3_0_config24_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_0_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_1_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_2_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_3_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_4_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_5_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_6_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_7_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_8_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_9_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_10_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_11_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_12_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_13_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_14_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_15_val : IN STD_LOGIC_VECTOR (7 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (21 downto 0) );
    end component;



begin
    grp_dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_29_11_5_3_0_config24_s_fu_95 : component gaussian_dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_29_11_5_3_0_config24_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_0_val => data_reg_273,
        data_1_val => data_57_reg_278,
        data_2_val => data_43_reg_283,
        data_3_val => data_44_reg_288,
        data_4_val => data_45_reg_293,
        data_5_val => data_46_reg_298,
        data_6_val => data_47_reg_303,
        data_7_val => data_48_reg_308,
        data_8_val => data_49_reg_313,
        data_9_val => data_50_reg_318,
        data_10_val => data_51_reg_323,
        data_11_val => data_52_reg_328,
        data_12_val => data_53_reg_333,
        data_13_val => data_54_reg_338,
        data_14_val => data_55_reg_343,
        data_15_val => data_56_reg_348,
        ap_return => grp_dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_29_11_5_3_0_config24_s_fu_95_ap_return);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((layer24_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                data_43_reg_283 <= layer33_cpy4_dout(23 downto 16);
                data_44_reg_288 <= layer33_cpy4_dout(31 downto 24);
                data_45_reg_293 <= layer33_cpy4_dout(39 downto 32);
                data_46_reg_298 <= layer33_cpy4_dout(47 downto 40);
                data_47_reg_303 <= layer33_cpy4_dout(55 downto 48);
                data_48_reg_308 <= layer33_cpy4_dout(63 downto 56);
                data_49_reg_313 <= layer33_cpy4_dout(71 downto 64);
                data_50_reg_318 <= layer33_cpy4_dout(79 downto 72);
                data_51_reg_323 <= layer33_cpy4_dout(87 downto 80);
                data_52_reg_328 <= layer33_cpy4_dout(95 downto 88);
                data_53_reg_333 <= layer33_cpy4_dout(103 downto 96);
                data_54_reg_338 <= layer33_cpy4_dout(111 downto 104);
                data_55_reg_343 <= layer33_cpy4_dout(119 downto 112);
                data_56_reg_348 <= layer33_cpy4_dout(127 downto 120);
                data_57_reg_278 <= layer33_cpy4_dout(15 downto 8);
                data_reg_273 <= data_fu_115_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                res_reg_353 <= grp_dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_29_11_5_3_0_config24_s_fu_95_ap_return;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, layer24_out_full_n, ap_CS_fsm_state13, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                if (((layer24_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;

    ap_ST_fsm_state13_blk_assign_proc : process(layer24_out_full_n)
    begin
        if ((layer24_out_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state13_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state13_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(real_start, ap_done_reg, layer33_cpy4_empty_n)
    begin
                ap_block_state1 <= ((layer33_cpy4_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, layer24_out_full_n, ap_CS_fsm_state13)
    begin
        if (((layer24_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    data_fu_115_p1 <= layer33_cpy4_dout(8 - 1 downto 0);

    internal_ap_ready_assign_proc : process(layer24_out_full_n, ap_CS_fsm_state13)
    begin
        if (((layer24_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    layer24_out_blk_n_assign_proc : process(layer24_out_full_n, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            layer24_out_blk_n <= layer24_out_full_n;
        else 
            layer24_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

        layer24_out_din <= std_logic_vector(IEEE.numeric_std.resize(signed(res_reg_353),29));


    layer24_out_write_assign_proc : process(layer24_out_full_n, ap_CS_fsm_state13)
    begin
        if (((layer24_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            layer24_out_write <= ap_const_logic_1;
        else 
            layer24_out_write <= ap_const_logic_0;
        end if; 
    end process;


    layer33_cpy4_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, layer33_cpy4_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer33_cpy4_blk_n <= layer33_cpy4_empty_n;
        else 
            layer33_cpy4_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer33_cpy4_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer33_cpy4_read <= ap_const_logic_1;
        else 
            layer33_cpy4_read <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
